name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [Desktop Chrome, Mobile Chrome]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run tests
        run: npx playwright test --project="${{ matrix.project }}"

      - name: Upload Playwright Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-repor

      - name: Get test summary
        id: test_summary
        run: |
          passed=$(cat test-results-${{ matrix.project }}.json | jq '[.suites[].specs[].tests[] | select(.status == "passed")] | length')
          failed=$(cat test-results-${{ matrix.project }}.json | jq '[.suites[].specs[].tests[] | select(.status == "failed")] | length')
          skipped=$(cat test-results-${{ matrix.project }}.json | jq '[.suites[].specs[].tests[] | select(.status == "skipped")] | length')
          echo "::set-output name=passed::$passed"
          echo "::set-output name=failed::$failed"
          echo "::set-output name=skipped::$skipped"

        # Send a notification to Slack with the results
      - name: Send Slack Notification
        if: always() # Ensure this step runs even if tests fail
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "text": ":robot_face: *Playwright Test Results*\nProject: ${{ matrix.project }}\n*Branch:* ${{ github.ref_name }}\n*Total Passed:* ${{ steps.test_summary.outputs.passed }}\n*Total Failed:* ${{ steps.test_summary.outputs.failed }}\n*Total Skipped:* ${{ steps.test_summary.outputs.skipped }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Playwright Test Results for ${{ matrix.project }}*\nBranch: ${{ github.ref_name }}\nCommit: <https://github.com/${{ github.repository }}/commit/${{ github.sha }}|View Commit>"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Passed:* ${{ steps.test_summary.outputs.passed }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Failed:* ${{ steps.test_summary.outputs.failed }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Skipped:* ${{ steps.test_summary.outputs.skipped }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Project:* ${{ matrix.project }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*View Workflow:* <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow>"
                  }
                ]
            }
            ]
          }' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
